#server
server:
  port: 9001

spring:
  application:
    name: blog-service
  datasource:
      druid:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/blog?characterEncoding=utf-8
        username: root
        password: root

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
